# Generated by Django 5.1.4 on 2025-01-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_rename_choide_test_answer_choice_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
