# Generated by Django 5.1.4 on 2025-01-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_rename_data_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votes',
            new_name='vote',
        ),
    ]
